### ISSUE TITLE
Explain virtualenv suggestion

### ISSUE THREAD

**Issue by matthias-ccri** [Tinche/bower-cache#3]
Hello,

Can you explain a little more about this part of the Readme:

> We strongly suggest installing into a virtualenv

I'm wondering, why is this a strong suggestion? This information may be useful for those who don't know much about virtualenv or python, but just want to use bower-cache. 

Because, I might be inclined to ignore the suggestion, and just install it outside a virtualenv, if the reason doesn't apply in my situation. But I don't know the reason _why_ this suggestion exists.

**Comment by Tinche** [comment]
Hello!

First of all, I'd like to point out this project is unmaintained at this point; I don't use it and I don't have the time for it. So if you use it you're kinda on your own, sorry :)

As for the virtualenv thing. To keep it short, if you're not installing it into a virtualenv you're installing it in a global location (either the system Python environment or the user Python environment); both options are worse than keeping it isolated in its own virtualenv. Here's a nice article on the matter: https://hynek.me/articles/python-deployment-anti-patterns/

**Comment by matthias-ccri** [comment]
Thanks! I'll close this issue.
